### ISSUE TITLE
When will it be open source?

### ISSUE THREAD

**Issue by luis-981102** [hjr37/CP-SLAM#1]

**Comment by hiyyg** [comment]
+1

**Comment by hjr37** [comment]
Thanks for your attention! We previously spent much time developing a real-time Gaussian-based SLAM system: [CG-SLAM](https://zju3dv.github.io/cg-slam/). In addition, considering the complexity of multi-thread code in multi-agent [CP-SLAM](https://zju3dv.github.io/cp-slam/), our open-source progress has been somewhat delayed. We are currently organizing and clearing the code for these two projects and we'll do our best to make them publicly available as soon as possible.
